services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - shared-networks

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - shared-networks

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - shared-networks

networks:
  shared-networks:
    name: shared-networks
    driver: bridge
    external: true
